<script>
	import falApi from '$lib/fal-api.svelte.js';

	let prompt = $state('');
	let isGenerating = $state(false);
	/** @type {string | null}*/
	let generatedImage = $state(null);
	let error = $state('');

	async function generateImage() {
		if (!prompt.trim()) {
			error = 'Please enter a prompt';
			return;
		}

		isGenerating = true;
		error = '';
		generatedImage = null;

		try {
			const imageUrl = await falApi.generateFluxImage(prompt);
			if (imageUrl) {
				generatedImage = imageUrl;
			} else {
				error = 'Failed to generate image';
			}
		} catch (/** @type {*} */ err) {
			error = `Error: ${err.message}`;
			console.error('Image generation error:', err);
		} finally {
			isGenerating = false;
		}
	}

	function clearImage() {
		generatedImage = null;
		error = '';
	}

	function downloadImage() {
		if (generatedImage) {
			const link = document.createElement('a');
			link.href = generatedImage;
			link.download = `fluxor-${Date.now()}.png`;
			link.click();
		}
	}

	/** @param {KeyboardEvent} event */
	function handleKeyPress(event) {
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			generateImage();
		}
	}
</script>

<div class="fluxor">
	<div class="fluxor-header">
		<h2>Fluxor - AI Image Generator</h2>
		<p>Powered by FLUX PRO 1.1 Ultra</p>
	</div>

	<div class="prompt-section">
		<label for="prompt-input">Enter your prompt:</label>
		<textarea
			id="prompt-input"
			bind:value={prompt}
			placeholder="Describe the image you want to generate..."
			onkeypress={handleKeyPress}
			disabled={isGenerating}
		></textarea>
		
		<div class="controls">
			<button 
				class="generate-btn" 
				onclick={generateImage} 
				disabled={isGenerating || !prompt.trim()}
			>
				{isGenerating ? 'Generating...' : 'Generate Image'}
			</button>
			
			{#if generatedImage}
				<button class="action-btn" onclick={clearImage}>Clear</button>
				<button class="action-btn" onclick={downloadImage}>Download</button>
			{/if}
		</div>
	</div>

	{#if error}
		<div class="error">
			⚠️ {error}
		</div>
	{/if}

	{#if isGenerating}
		<div class="loading">
			<div class="loading-spinner"></div>
			<p>Generating your image... This may take a moment.</p>
		</div>
	{/if}

	{#if generatedImage}
		<div class="image-result">
			<img src={generatedImage} alt="Thing generated by the model using the prompt" />
		</div>
	{/if}
</div>

<style>
	.fluxor {
		display: flex;
		flex-direction: column;
		height: 100%;
		font-family: 'MS Sans Serif', 'Microsoft Sans Serif', 'Tahoma', sans-serif;
		background: var(--theme-window);
		color: var(--theme-text);
	}

	.fluxor-header {
		padding: 8px;
		border-bottom: 1px solid #808080;
		background: var(--theme-window);
	}

	.fluxor-header h2 {
		margin: 0;
		font-size: 14px;
		font-weight: bold;
		color: var(--theme-text);
	}

	.fluxor-header p {
		margin: 2px 0 0 0;
		font-size: 10px;
		color: #666;
	}

	.prompt-section {
		padding: 8px;
		border-bottom: 1px solid #808080;
	}

	.prompt-section label {
		display: block;
		margin-bottom: 4px;
		font-size: 11px;
		font-weight: bold;
	}

	.prompt-section textarea {
		width: 100%;
		height: 60px;
		border: 1px inset var(--theme-windowBorder);
		padding: 4px;
		font-family: inherit;
		font-size: 11px;
		resize: vertical;
		background: white;
		color: black;
		box-sizing: border-box;
	}

	.prompt-section textarea:disabled {
		background: #f0f0f0;
		color: #666;
	}

	.controls {
		display: flex;
		gap: 4px;
		margin-top: 8px;
		align-items: center;
	}

	.generate-btn {
		padding: 4px 12px;
		border: 1px outset var(--theme-button);
		background: var(--theme-button);
		color: var(--theme-buttonText);
		font-size: 11px;
		font-weight: bold;
		cursor: pointer;
		font-family: inherit;
	}

	.generate-btn:disabled {
		background: #d0d0d0;
		color: #808080;
		cursor: not-allowed;
		border: 1px inset var(--theme-button);
	}

	.generate-btn:not(:disabled):active {
		border: 1px inset var(--theme-button);
	}

	.action-btn {
		padding: 4px 8px;
		border: 1px outset var(--theme-button);
		background: var(--theme-button);
		color: var(--theme-buttonText);
		font-size: 11px;
		cursor: pointer;
		font-family: inherit;
	}

	.action-btn:active {
		border: 1px inset var(--theme-button);
	}

	.error {
		padding: 8px;
		background: #ffdddd;
		border: 1px solid #cc0000;
		color: #cc0000;
		font-size: 11px;
		margin: 4px 8px;
	}

	.loading {
		display: flex;
		flex-direction: column;
		align-items: center;
		padding: 20px;
		text-align: center;
	}

	.loading-spinner {
		width: 32px;
		height: 32px;
		border: 3px solid var(--theme-button);
		border-top: 3px solid var(--theme-windowHeader);
		border-radius: 50%;
		animation: spin 1s linear infinite;
		margin-bottom: 8px;
	}

	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}

	.loading p {
		margin: 0;
		font-size: 11px;
		color: var(--theme-text);
	}

	.image-result {
		flex: 1;
		padding: 8px;
		overflow: auto;
		text-align: center;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.image-result img {
		max-width: 100%;
		max-height: 100%;
		border: 1px solid #808080;
		box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
		background: white;
	}
</style>